default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  primary:
    adapter: sqlite3
    database: storage/development.sqlite3
    <<: *default
  queue:
    adapter: sqlite3
    database: storage/development.sqlite3
    <<: *default

test:
  primary:
    adapter: sqlite3
    database: storage/test.sqlite3
    <<: *default
  queue:
    adapter: sqlite3
    database: storage/test.sqlite3
    <<: *default

production:
  primary:
    url: <%= ENV["DATABASE_URL"] %>
    <<: *default
  queue:
    url: <%= ENV["DATABASE_URL"] %>
    <<: *default