default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  adapter: sqlite3
  database: storage/development.sqlite3
  <<: *default

test:
  adapter: sqlite3
  database: storage/test.sqlite3
  <<: *default

production:
  url: <%= ENV.fetch("DATABASE_URL") %>
  <<: *default